<!doctype html><html class=no-js lang=en-us><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta http-equiv=x-ua-compatible content="IE=edge"><title>Error Handling in JavaScript - Coding N Concepts</title><script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script><meta name=description content="In this tutorial, we'll learn error handling using try, catch, finally and throw statements. We'll also learn about built-in JavaScript error objects (Error, SyntaxError, ReferenceError, etc.) and how to define custom errors."><meta property="og:title" content="Error Handling in JavaScript"><meta property="og:description" content="In this tutorial, we'll learn error handling using try, catch, finally and throw statements. We'll also learn about built-in JavaScript error objects (Error, SyntaxError, ReferenceError, etc.) and how to define custom errors."><meta property="og:type" content="article"><meta property="og:url" content="https://codingnconcepts.com/javascript/error-handling-in-javascript/"><meta property="og:image" content="https://codingnconcepts.com/img/logo/js.png"><meta property="article:published_time" content="2020-07-14T00:00:00+00:00"><meta property="article:modified_time" content="2020-07-17T00:00:00+00:00"><meta property="og:site_name" content="CodingNConcepts"><meta property="article:author" content="https://www.facebook.com/codingnconcepts"><meta property="article:publisher" content="https://www.facebook.com/codingnconcepts"><meta property="article:section" content="javascript"><meta property="article:tag" content="Javascript Core"><meta property="fb:admins" content="177784346770196"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://codingnconcepts.com/img/logo/js.png"><meta name=twitter:title content="Error Handling in JavaScript"><meta name=twitter:description content="In this tutorial, we'll learn error handling using try, catch, finally and throw statements. We'll also learn about built-in JavaScript error objects (Error, SyntaxError, ReferenceError, etc.) and how to define custom errors."><link rel=dns-prefetch href=//fonts.googleapis.com><link rel=dns-prefetch href=//fonts.gstatic.com><link rel=stylesheet href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700|Rowdies"><link rel=stylesheet href=/css/style.css><link rel="shortcut icon" href=/favicon.ico><link rel=canonical href=https://codingnconcepts.com/javascript/error-handling-in-javascript/><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;ga('create','UA-160024498-1','auto');ga('send','pageview');}</script><script async src=https://www.google-analytics.com/analytics.js></script><script type=application/ld+json>{"@context":"http://schema.org","@type":"BlogPosting","articleSection":"javascript","name":"Error Handling in JavaScript","headline":"Error Handling in JavaScript","alternativeHeadline":"","description":"In this tutorial, we\x27ll learn error handling using try, catch, finally and throw statements. We\x27ll also learn about built-in JavaScript error objects (Error, SyntaxError, ReferenceError, etc.) and how to define custom errors.","inLanguage":"en-us","isFamilyFriendly":"true","mainEntityOfPage":{"@type":"WebPage","@id":"https:\/\/codingnconcepts.com\/javascript\/error-handling-in-javascript\/"},"author":{"@type":"Person","name":"Ashish Lahoti"},"creator":{"@type":"Person","name":"Ashish Lahoti"},"accountablePerson":{"@type":"Person","name":"Ashish Lahoti"},"copyrightHolder":"Coding N Concepts","copyrightYear":"2020","dateCreated":"2020-07-14T00:00:00.00Z","datePublished":"2020-07-14T00:00:00.00Z","dateModified":"2020-07-17T00:00:00.00Z","publisher":{"@type":"Organization","name":"Coding N Concepts","url":"https://codingnconcepts.com/","logo":{"@type":"ImageObject","url":"https:\/\/codingnconcepts.com\/favicon-32x32.png","width":"32","height":"32"}},"image":["https://codingnconcepts.com/img/logo/js.png"],"url":"https:\/\/codingnconcepts.com\/javascript\/error-handling-in-javascript\/","wordCount":"1428","genre":["Javascript Core"],"keywords":null}</script></head><body class=body><div class="container container--outer"><header class=header><div class=container><div class=logo><a class=logo__link href=/ title="Coding N Concepts" rel=home><div class=logo__title><img src=/favicon-32x32.png alt="Error Handling in JavaScript"> Coding N Concepts</div><div class=logo__tagline>Ashish Lahoti's Technical Blog</div></a></div><nav class=menu><button class=menu__btn aria-haspopup=true aria-expanded=false tabindex=0>
<span class=menu__btn-title tabindex=-1>Menu</span></button><ul class=menu__list><li class=menu__item><a class=menu__link href=/><span class=menu__text>Home</span></a></li><li class=menu__item><a class=menu__link href=/tags/popular-posts><span class=menu__text>Popular</span></a></li><li class="menu__item menu__dropdown"><a class=menu__link href=/java/><span class=menu__text>Java</span>
<label class=drop-icon for=Java>▾</label></a>
<input type=checkbox id=Java><ul class=submenu__list><li class=menu__item><a class=menu__link href=/tags/java-core/><span class=menu__text>Core Java</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-collection/><span class=menu__text>Collections</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-design-pattern/><span class=menu__text>Design Patterns</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-recursive/><span class=menu__text>Recursive</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-streams/><span class=menu__text>Streams</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-string/><span class=menu__text>String</span></a></li><li class=menu__item><a class=menu__link href=/tags/java-threads/><span class=menu__text>Threads</span></a></li></ul></li><li class="menu__item menu__dropdown"><a class=menu__link href=/javascript/><span class=menu__text>JavaScript</span>
<label class=drop-icon for=JavaScript>▾</label></a>
<input type=checkbox id=JavaScript><ul class=submenu__list><li class=menu__item><a class=menu__link href=/tags/javascript-core/><span class=menu__text>JS Core</span></a></li><li class=menu__item><a class=menu__link href=/tags/javascript-array/><span class=menu__text>JS Array</span></a></li><li class=menu__item><a class=menu__link href=/tags/javascript-console/><span class=menu__text>JS Console</span></a></li><li class=menu__item><a class=menu__link href=/tags/javascript-es6/><span class=menu__text>ES6</span></a></li></ul></li><li class="menu__item menu__dropdown"><a class=menu__link href=/spring-boot/><span class=menu__text>Spring Boot</span>
<label class=drop-icon for="Spring Boot">▾</label></a>
<input type=checkbox id="Spring Boot"><ul class=submenu__list><li class=menu__item><a class=menu__link href=/tags/spring-boot-basics/><span class=menu__text>Spring Boot Basics</span></a></li><li class=menu__item><a class=menu__link href=/tags/spring-boot-rest/><span class=menu__text>Spring Boot REST</span></a></li><li class=menu__item><a class=menu__link href=/tags/spring-boot-kafka/><span class=menu__text>Spring Boot KAFKA</span></a></li></ul></li><li class="menu__item menu__dropdown"><a class=menu__link href=/puzzle/><span class=menu__text>Puzzles</span>
<label class=drop-icon for=Puzzles>▾</label></a>
<input type=checkbox id=Puzzles><ul class=submenu__list><li class=menu__item><a class=menu__link href=/tags/maths-puzzle/><span class=menu__text>Maths Puzzles</span></a></li><li class=menu__item><a class=menu__link href=/tags/weight-puzzle/><span class=menu__text>Weight Puzzles</span></a></li></ul></li><li class="menu__item menu__dropdown"><a class=menu__link href=/interview-questions/><span class=menu__text>Interview Q&A</span>
<label class=drop-icon for="Interview Q&A">▾</label></a>
<input type=checkbox id="Interview Q&A"><ul class=submenu__list><li class=menu__item><a class=menu__link href=/tags/java-qa/><span class=menu__text>Java</span></a></li><li class=menu__item><a class=menu__link href=/tags/javascript-qa/><span class=menu__text>JavaScript</span></a></li><li class=menu__item><a class=menu__link href=/tags/css-qa/><span class=menu__text>CSS</span></a></li><li class=menu__item><a class=menu__link href=/tags/spring-qa/><span class=menu__text>Spring</span></a></li><li class=menu__item><a class=menu__link href=/tags/microservice-qa/><span class=menu__text>Microservices</span></a></li></ul></li><li class=menu__item><a class=menu__link href=/hugo/><span class=menu__text>Hugo</span></a></li><li class=menu__item><a class=menu__link href=/about/><span class=menu__text>About Me</span></a></li></ul></nav></div></header><div class="wrapper flex"><div class=primary><main class=main role=main><article class=post autonumbering><header class=post__header><h1 class=post__title><img class=post__thumbnail src=/img/logo/js.png alt="Error Handling in JavaScript"> Error Handling in JavaScript</h1><div class="post__meta meta"><div class="meta__item-author meta__item"><svg class="meta__icon icon icon-author" width="16" height="16" viewBox="0 0 12 16"><path d="M6 1c2.2.0 3.5 2 3.5 4.5C9.5 7 8.9 8.2 8 9c2.9.8 4 2.5 4 5v1H0v-1c0-2.5 1.1-4.2 4-5-.9-.8-1.5-2-1.5-3.5C2.5 3 3.8 1 6 1z"/></svg><span class=meta__text>Ashish Lahoti</span></div><div class="meta__item-datetime meta__item"><svg class="meta__icon icon icon-time" width="16" height="14" viewBox="0 0 30 28"><path d="M15 0C7 0 1 6 1 14s6 14 14 14 14-6 14-14S23 0 15 0zm0 25C9 25 4 20 4 14S9 3 15 3s11 5 11 11-5 11-11 11zm1-18h-2v8.4l6.8 4.4L22 18l-6-3.8V7z"/></svg><time class=meta__text datetime=2020-07-14T00:00:00Z>July 14, 2020</time>
<time class=meta__text datetime=2020-07-17T00:00:00Z>(Last Modified: July 17, 2020)</time></div><div class="meta__item-categories meta__item"><svg class="meta__icon icon icon-category" width="16" height="16" viewBox="0 0 16 16"><path d="m7 2 1 2h8v11H0V2z"/></svg><span class=meta__text><a class=meta__link href=/categories/javascript/ rel=category>Javascript</a></span></div></div></header><div class="post__toc toc"><div class=toc__title>Page content</div><div class=toc__menu><nav id=TableOfContents><ul><li><a href=#using-trycatchfinallythrow>Using <code>try..catch..finally..throw</code></a><ul><li><a href=#try><code>try</code></a></li><li><a href=#trycatch><code>try..catch</code></a></li><li><a href=#tryfinally><code>try..finally</code></a></li><li><a href=#trycatchfinally><code>try..catch..finally</code></a></li><li><a href=#throw><code>throw</code></a></li></ul></li><li><a href=#error-handling-in-asynchronous-code>Error handling in asynchronous Code</a><ul><li><a href=#thencatch-with-promises><code>then..catch</code> with Promises</a></li><li><a href=#trycatch-with-async-await><code>try..catch</code> with async await</a></li></ul></li><li><a href=#built-in-javascript-errors>Built-In JavaScript Errors</a><ul><li><a href=#error>Error</a></li><li><a href=#evalerror>EvalError</a></li><li><a href=#rangeerror>RangeError</a></li><li><a href=#referenceerror>ReferenceError</a></li><li><a href=#syntaxerror>SyntaxError</a></li><li><a href=#typeerror>TypeError</a></li><li><a href=#urierror>URIError</a></li></ul></li><li><a href=#define-and-throw-custom-error>Define and throw Custom Error</a></li></ul></nav></div></div><div class="content post__content clearfix"><p>In this tutorial, we&rsquo;ll learn error handling using <code>try</code>, <code>catch</code>, <code>finally</code> and <code>throw</code> statements. We&rsquo;ll also learn about built-in JavaScript error objects <em>(Error, SyntaxError, ReferenceError, etc.)</em> and how to define custom errors.</p><h2 id=using-trycatchfinallythrow>Using <code>try..catch..finally..throw</code></h2><p>We use <code>try</code>, <code>catch</code>, <code>finally</code> and <code>throw</code> keywords in error handling in JavaScript.</p><ol><li>The <code>try</code> block wrap your code to check for errors.</li><li>The <code>throw</code> keyword is used to throw custom errors.</li><li>The <code>catch</code> block handle the caught errors. You chain <code>catch</code> block with <code>try</code> block.</li><li>The <code>finally</code> block of code is always executed regardless of the result. You chain <code>finally</code> block with <code>try</code> and <code>catch</code> block.<br><br></li></ol><h3 id=try><code>try</code></h3><p>Every <code>try</code> block must be chained with at least one of the <code>catch</code> or <code>finally</code> block otherwise <em>SyntaxError</em> will be thrown.</p><p>Let&rsquo;s use <code>try</code> block alone to verify:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);
}
</code></pre></div><pre><code><span style=color:red>ⓧ Uncaught SyntaxError: Missing catch or finally after try</span>
</code></pre><p><br></p><h3 id=trycatch><code>try..catch</code></h3><p>It is <strong>recommended</strong> to use <code>try</code> with <code>catch</code> block which handles the error gracefully thrown by <code>try</code> block.</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
}
</code></pre></div><pre><code>➤ <span style=color:red>ⓧ Error while executing the code</span>
</code></pre><h4 id=trycatch-with-invalid-code>try..catch with invalid code</h4><p>The <code>try..catch</code> cannot catch the exception of invalid JavaScript code, for example the below code in <code>try</code> block is syntactically wrong and cannot be caught by <code>catch</code> block.</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#f92672>~!</span><span style=color:#a6e22e>$</span><span style=color:#f92672>%^&amp;*</span>
} <span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;code execution will never reach here&#34;</span>);
}
</code></pre></div><pre><code>➤ <span style=color:red>ⓧ Uncaught SyntaxError: Invalid or unexpected token</span>
</code></pre><h4 id=trycatch-with-asynchronous-code>try..catch with asynchronous code</h4><p>Similarly <code>try..catch</code> cannot catch the exception thrown inside asynchronous code which will be executed later such as <code>setTimeout</code></p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#a6e22e>setTimeout</span>(<span style=color:#66d9ef>function</span>() {
    <span style=color:#a6e22e>noSuchVariable</span>;   <span style=color:#75715e>// undefined variable
</span><span style=color:#75715e></span>  }, <span style=color:#ae81ff>1000</span>);
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;code execution will never reach here&#34;</span>);
}
</code></pre></div><p>Uncaught ReferenceError will be thrown after 1s</p><pre><code>➤ <span style=color:red>ⓧ Uncaught ReferenceError: noSuchVariable is not definedn</span>
</code></pre><p>We should use <code>try..catch</code> inside asynchronous code to handle the error gracefully in this way</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#a6e22e>setTimeout</span>(<span style=color:#66d9ef>function</span>() {
  <span style=color:#66d9ef>try</span> {
    <span style=color:#a6e22e>noSuchVariable</span>;
  } <span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span>) {
    <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;error is caught here!&#34;</span>);
  }
}, <span style=color:#ae81ff>1000</span>);
</code></pre></div><h4 id=nested-trycatch>Nested try..catch</h4><p>We can also use nested <code>try</code> and <code>catch</code> blocks and throw an error upwards like this:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#66d9ef>try</span> {
    <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the inner code&#39;</span>);
  } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
    <span style=color:#66d9ef>throw</span> <span style=color:#a6e22e>err</span>;
  }
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;Error caught by outer block:&#34;</span>);
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
}
</code></pre></div><pre><code>Error caught by outer block:
➤ <span style=color:red>ⓧ Error while executing the code</span>
</code></pre><p><br></p><h3 id=tryfinally><code>try..finally</code></h3><p>It is <strong>not recommended</strong> to use <code>try</code> with <code>finally</code> (without using <code>catch</code> block in between). Let&rsquo;s see what happens:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);
} <span style=color:#66d9ef>finally</span> {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#39;finally&#39;</span>);
}
</code></pre></div><pre><code>finally
➤ <span style=color:red>ⓧ Uncaught Error: Error while executing the code</span>
</code></pre><p>We should note two things here:</p><ol><li>The <code>finally</code> block is executed even after error is thrown from <code>try</code> block</li><li>Error is not handled gracefully without <code>catch</code> block resulting in <em>Uncaught Error</em></li></ol><p><br></p><h3 id=trycatchfinally><code>try..catch..finally</code></h3><p>It is <strong>recommended</strong> to use <code>try</code> with <code>catch</code> block and optional <code>finally</code> block.</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;Start of try block&#34;</span>);
  <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;End of try block -- never reached&#34;</span>);
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
} <span style=color:#66d9ef>finally</span> {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#39;Finally block always run&#39;</span>);
}
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;Code execution outside try-catch-finally block continue..&#34;</span>);
</code></pre></div><pre><code>Start of try block
➤ <span style=color:red>ⓧ Error while executing the code</span>
Finally block always run
Code execution outside try-catch-finally block continue..
</code></pre><p>We should note two things here as well:</p><ol><li>The code after throwing error in <code>try</code> block never reached.</li><li>Error is handled gracefully this time by <code>catch</code> block.</li><li>The <code>finally</code> block is executed even after error is thrown from <code>try</code> block.</li></ol><p>The <code>finally</code> block is generally used for cleaning up resources or closing the streams such as below:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span> {
  <span style=color:#a6e22e>openFile</span>(<span style=color:#a6e22e>file</span>);
  <span style=color:#a6e22e>readFile</span>(<span style=color:#a6e22e>file</span>);
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
} <span style=color:#66d9ef>finally</span> {
  <span style=color:#a6e22e>closeFile</span>(<span style=color:#a6e22e>file</span>);
}
</code></pre></div><p><br></p><h3 id=throw><code>throw</code></h3><p>The <code>throw</code> statement is used to throw an exception.</p><pre><code>throw &lt;expression&gt;
</code></pre><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#75715e>// throw primitives and functions
</span><span style=color:#75715e></span><span style=color:#66d9ef>throw</span> <span style=color:#e6db74>&#34;Error404&#34;</span>;
<span style=color:#66d9ef>throw</span> <span style=color:#ae81ff>42</span>;
<span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>true</span>;
<span style=color:#66d9ef>throw</span> {<span style=color:#a6e22e>toString</span><span style=color:#f92672>:</span> <span style=color:#66d9ef>function</span>() { <span style=color:#66d9ef>return</span> <span style=color:#e6db74>&#34;I&#39;m an object!&#34;</span>; } };

<span style=color:#75715e>// throw error object
</span><span style=color:#75715e></span><span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);
<span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>SyntaxError</span>(<span style=color:#e6db74>&#39;Something is wrong with the syntax&#39;</span>);
<span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>ReferenceError</span>(<span style=color:#e6db74>&#39;Oops..Wrong reference&#39;</span>);

<span style=color:#75715e>// throw custom error object
</span><span style=color:#75715e></span><span style=color:#66d9ef>function</span> <span style=color:#a6e22e>ValidationError</span>(<span style=color:#a6e22e>message</span>) {
  <span style=color:#66d9ef>this</span>.<span style=color:#a6e22e>message</span> <span style=color:#f92672>=</span> <span style=color:#a6e22e>message</span>;
  <span style=color:#66d9ef>this</span>.<span style=color:#a6e22e>name</span> <span style=color:#f92672>=</span> <span style=color:#e6db74>&#39;ValidationError&#39;</span>;
}
<span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>ValidationError</span>(<span style=color:#e6db74>&#39;Value too high&#39;</span>);
</code></pre></div><h2 id=error-handling-in-asynchronous-code>Error handling in asynchronous Code</h2><p>It is recommended to use Promises and async await for asynchronous code (API calls) as they provide support for error handling.</p><h3 id=thencatch-with-promises><code>then..catch</code> with Promises</h3><p>You can chain multiple Promises using <code>then()</code> along with <code>catch()</code> to handle errors of individual promise in the chain like this:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js>Promise.<span style=color:#a6e22e>resolve</span>(<span style=color:#ae81ff>1</span>)
  .<span style=color:#a6e22e>then</span>(<span style=color:#a6e22e>res</span> =&gt; {
      <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#a6e22e>res</span>);  <span style=color:#75715e>// prints &#39;1&#39;
</span><span style=color:#75715e></span>
      <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;something went wrong&#39;</span>);  <span style=color:#75715e>// throw error
</span><span style=color:#75715e></span>
      <span style=color:#66d9ef>return</span> Promise.<span style=color:#a6e22e>resolve</span>(<span style=color:#ae81ff>2</span>);  <span style=color:#75715e>// code will not reach here
</span><span style=color:#75715e></span>  })
  .<span style=color:#a6e22e>then</span>(<span style=color:#a6e22e>res</span> =&gt; {
      <span style=color:#75715e>// code will not reach since promise not resolved in prev block here due to error
</span><span style=color:#75715e></span>      <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#a6e22e>res</span>);    
  })
  .<span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span> =&gt; {
      <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);  <span style=color:#75715e>// prints &#39;something went wrong&#39;
</span><span style=color:#75715e></span>      <span style=color:#66d9ef>return</span> Promise.<span style=color:#a6e22e>resolve</span>(<span style=color:#ae81ff>3</span>);
  })
  .<span style=color:#a6e22e>then</span>(<span style=color:#a6e22e>res</span> =&gt; {
      <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#a6e22e>res</span>);  <span style=color:#75715e>// prints &#39;3&#39;
</span><span style=color:#75715e></span>  })
  .<span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span> =&gt; {
      <span style=color:#75715e>// code will not reach since promise resolved in prev block
</span><span style=color:#75715e></span>      <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>);
  })
</code></pre></div><p>Let&rsquo;s look at the more practical example where we call an API using <code>fetch</code> which returns a promise object. We handle the API failure gracefully using <code>catch</code> block.</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>function</span> <span style=color:#a6e22e>handleErrors</span>(<span style=color:#a6e22e>response</span>) {
    <span style=color:#66d9ef>if</span> (<span style=color:#f92672>!</span><span style=color:#a6e22e>response</span>.<span style=color:#a6e22e>ok</span>) {
        <span style=color:#66d9ef>throw</span> Error(<span style=color:#a6e22e>response</span>.<span style=color:#a6e22e>statusText</span>);
    }
    <span style=color:#66d9ef>return</span> <span style=color:#a6e22e>response</span>;
}

<span style=color:#a6e22e>fetch</span>(<span style=color:#e6db74>&#34;http://httpstat.us/500&#34;</span>)
    .<span style=color:#a6e22e>then</span>(<span style=color:#a6e22e>handleErrors</span>)
    .<span style=color:#a6e22e>then</span>(<span style=color:#a6e22e>response</span> =&gt; <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;ok&#34;</span>))
    .<span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>error</span> =&gt; <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;Caught&#34;</span>, <span style=color:#a6e22e>error</span>));
</code></pre></div><pre><code>Caught Error: Internal Server Error
    at handleErrors (&lt;anonymous&gt;:3:15)
</code></pre><p><br></p><h3 id=trycatch-with-async-await><code>try..catch</code> with async await</h3><p>It is very easy to handle errors using <code>try..catch</code> when handling asynchronous with async await like this:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js>(<span style=color:#a6e22e>async</span> <span style=color:#66d9ef>function</span>() {
    <span style=color:#66d9ef>try</span> {
        <span style=color:#a6e22e>await</span> <span style=color:#a6e22e>fetch</span>(<span style=color:#e6db74>&#34;http://httpstat.us/500&#34;</span>);
    } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>err</span>) {
        <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>error</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
    }
})();
</code></pre></div><p>Let&rsquo;s look at the same example where we call an API using <code>fetch</code> which returns a promise object. We handle the API failure gracefully using <code>try..catch</code> block.</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>function</span> <span style=color:#a6e22e>handleErrors</span>(<span style=color:#a6e22e>response</span>) {
    <span style=color:#66d9ef>if</span> (<span style=color:#f92672>!</span><span style=color:#a6e22e>response</span>.<span style=color:#a6e22e>ok</span>) {
        <span style=color:#66d9ef>throw</span> Error(<span style=color:#a6e22e>response</span>.<span style=color:#a6e22e>statusText</span>);
    }
}

(<span style=color:#a6e22e>async</span> <span style=color:#66d9ef>function</span>() {
    <span style=color:#66d9ef>try</span> {
      <span style=color:#66d9ef>let</span> <span style=color:#a6e22e>response</span> <span style=color:#f92672>=</span> <span style=color:#a6e22e>await</span> <span style=color:#a6e22e>fetch</span>(<span style=color:#e6db74>&#34;http://httpstat.us/500&#34;</span>);
      <span style=color:#a6e22e>handleErrors</span>(<span style=color:#a6e22e>response</span>);
      <span style=color:#66d9ef>let</span> <span style=color:#a6e22e>data</span> <span style=color:#f92672>=</span> <span style=color:#a6e22e>await</span> <span style=color:#a6e22e>response</span>.<span style=color:#a6e22e>json</span>();
      <span style=color:#66d9ef>return</span> <span style=color:#a6e22e>data</span>;
    } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>error</span>) {
        <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;Caught&#34;</span>, <span style=color:#a6e22e>error</span>)
    }
})();
</code></pre></div><pre><code>Caught Error: Internal Server Error
    at handleErrors (&lt;anonymous&gt;:3:15)
    at &lt;anonymous&gt;:11:7
</code></pre><h2 id=built-in-javascript-errors>Built-In JavaScript Errors</h2><h3 id=error>Error</h3><p>JavaScript has built-in <strong>Error Object</strong> which is generally thrown by <code>try</code> block and caught in <code>catch</code> block.</p><p>Error Object consist of following properties:</p><ul><li><strong>name:</strong> is the name of the error for e.g. &ldquo;Error&rdquo;, &ldquo;SyntaxError&rdquo;, &ldquo;ReferenceError&rdquo; etc.</li><li><strong>message:</strong> is the message about error details</li><li><strong>stack:</strong> is the stack trace of the error used for debugging purpose.</li></ul><p>Let&rsquo;s create an Error Object and look at its name and message property:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>const</span> <span style=color:#a6e22e>err</span> <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> Error(<span style=color:#e6db74>&#39;Error while executing the code&#39;</span>);

<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;name:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>name</span>);
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;message:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;stack:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>stack</span>);
</code></pre></div><pre><code>name: Error
message: Error while executing the code
stack: Error: Error while executing the code
    at &lt;anonymous&gt;:1:13
</code></pre><p>JavaScript has following built-in errors which are inherited from the Error Object:</p><h3 id=evalerror>EvalError</h3><p>The <em>EvalError</em> indicates an error regarding the global <code>eval()</code> function. This exception is not thrown by JavaScript anymore and it exist for backward compatibility.</p><h3 id=rangeerror>RangeError</h3><p>The <em>RangeError</em> is thrown when a value out of range.</p><pre><code>➤ [].length = -1
<span style=color:red>ⓧ Uncaught RangeError: Invalid array length</span>
</code></pre><h3 id=referenceerror>ReferenceError</h3><p>The <em>ReferenceError</em> is thrown when a variable is referenced which does not exist.</p><pre><code>➤ x = x + 1;
<span style=color:red>ⓧ Uncaught ReferenceError: x is not defined</span>
</code></pre><h3 id=syntaxerror>SyntaxError</h3><p>The <em>SyntaxError</em> is thrown when you have used any wrong syntax in JavaScript code.</p><pre><code>➤ function() { return 'Hi!' }
<span style=color:red>ⓧ Uncaught SyntaxError: Function statements require a function name</span>

➤ 1 = 1
<span style=color:red>ⓧ Uncaught SyntaxError: Invalid left-hand side in assignment</span>

➤ JSON.parse(&quot;{ x }&quot;);
<span style=color:red>ⓧ Uncaught SyntaxError: Unexpected token x in JSON at position 2</span>
</code></pre><h3 id=typeerror>TypeError</h3><p>The <em>TypeError</em> is thrown when the value is not of the expected type.</p><pre><code>➤ 1();
<span style=color:red>ⓧ Uncaught TypeError: 1 is not a function</span>

➤ null.name;
<span style=color:red>ⓧ Uncaught TypeError: Cannot read property &#39;name&#39; of null</span>
</code></pre><h3 id=urierror>URIError</h3><p>The <em>URIError</em> is thrown when global URI handling function was used in a wrong way.</p><pre><code>➤ decodeURI(&quot;%%%&quot;);
<span style=color:red>ⓧ Uncaught URIError: URI malformed</span>
</code></pre><h2 id=define-and-throw-custom-error>Define and throw Custom Error</h2><p>We can also define our custom error in this way:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>class</span> <span style=color:#a6e22e>CustomError</span> <span style=color:#66d9ef>extends</span> Error {
  <span style=color:#a6e22e>constructor</span>(<span style=color:#a6e22e>message</span>) {
    <span style=color:#66d9ef>super</span>(<span style=color:#a6e22e>message</span>);
    <span style=color:#66d9ef>this</span>.<span style=color:#a6e22e>name</span> <span style=color:#f92672>=</span> <span style=color:#e6db74>&#34;CustomError&#34;</span>;
  } 
};

<span style=color:#66d9ef>const</span> <span style=color:#a6e22e>err</span> <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>CustomError</span>(<span style=color:#e6db74>&#39;Custom error while executing the code&#39;</span>);

<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;name:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>name</span>);
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;message:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
</code></pre></div><pre><code>name: CustomError
message: Custom error while executing the code
</code></pre><p>We can further enhance our <em>CustomError</em> object to include error code as well:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>class</span> <span style=color:#a6e22e>CustomError</span> <span style=color:#66d9ef>extends</span> Error {
  <span style=color:#a6e22e>constructor</span>(<span style=color:#a6e22e>message</span>, <span style=color:#a6e22e>code</span>) {
    <span style=color:#66d9ef>super</span>(<span style=color:#a6e22e>message</span>);
    <span style=color:#66d9ef>this</span>.<span style=color:#a6e22e>name</span> <span style=color:#f92672>=</span> <span style=color:#e6db74>&#34;CustomError&#34;</span>;
    <span style=color:#66d9ef>this</span>.<span style=color:#a6e22e>code</span> <span style=color:#f92672>=</span> <span style=color:#a6e22e>code</span>;
  } 
};

<span style=color:#66d9ef>const</span> <span style=color:#a6e22e>err</span> <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>CustomError</span>(<span style=color:#e6db74>&#39;Custom error while executing the code&#39;</span>, <span style=color:#e6db74>&#34;ERROR_CODE&#34;</span>);

<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;name:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>name</span>);
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;message:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
<span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#e6db74>&#34;code:&#34;</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>code</span>);
</code></pre></div><pre><code>name: CustomError
message: Custom error while executing the code
code: ERROR_CODE
</code></pre><p>Let&rsquo;s use this in <code>try..catch</code> block:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-js data-lang=js><span style=color:#66d9ef>try</span>{
  <span style=color:#66d9ef>try</span> {
    <span style=color:#66d9ef>null</span>.<span style=color:#a6e22e>name</span>;
  }<span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span>){
    <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>CustomError</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>name</span>);  <span style=color:#75715e>//message, code
</span><span style=color:#75715e></span>  }
}<span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>err</span>){
  <span style=color:#a6e22e>console</span>.<span style=color:#a6e22e>log</span>(<span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>name</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>code</span>, <span style=color:#a6e22e>err</span>.<span style=color:#a6e22e>message</span>);
}
</code></pre></div><pre><code>CustomError TypeError Cannot read property 'name' of null
</code></pre></div><footer class=post__footer><div class="post__tags tags clearfix"><svg class="tags__badge icon icon-tag" width="16" height="16" viewBox="0 0 32 32"><path d="M32 19c0 1-1 2-1 2L21 31s-1 1-2 1-2-1-2-1L2 16c-1-1-1.4-2-1.4-2S0 12.5.0 11V3C0 1.5.8.8.8.8S1.5.0 3 0h8c1.5.0 3 .6 3 .6S15 1 16 2l15 15s1 1 1 2zM7 10a3 3 0 100-6 3 3 0 000 6z"/></svg><ul class=tags__list><li class=tags__item><a class="tags__link btn" href=/tags/javascript-core/ rel=tag>Javascript Core</a></li></ul></div></footer></article></main><section class=social-share><ul class=share-icons><li><a href="https://twitter.com/intent/tweet?hashtags=codingnconcepts&url=https%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f&text=Error%20Handling%20in%20JavaScript" target=_blank rel=noopener aria-label="Share on Twitter" class="share-btn twitter"><svg class="widget-social__link-icon icon icon-twitter" width="24" height="24" viewBox="0 0 384 312"><path d="m384 36.9c-14.1 6.3-29.3 10.5-45.2 12.4 16.3-9.7 28.8-25.2 34.6-43.6-15.2 9-32.1 15.6-50 19.1-14.4-15.2-34.9-24.8-57.5-24.8-43.5.0-78.8 35.3-78.8 78.8.0 6.2.7 12.2 2 17.9-65.5-3.3-123.5-34.6-162.4-82.3-6.7 11.6-10.6 25.2-10.6 39.6.0 27.3 13.9 51.4 35 65.6-12.9-.4-25.1-4-35.7-9.9v1c0 38.2 27.2 70 63.2 77.2-6.6 1.8-13.6 2.8-20.8 2.8-5.1.0-10-.5-14.8-1.4 10 31.3 39.1 54.1 73.6 54.7-27 21.1-60.9 33.7-97.8 33.7-6.4.0-12.6-.4-18.8-1.1 34.9 22.4 76.3 35.4 120.8 35.4 144.9.0 224.1-120 224.1-224.1.0-3.4-.1-6.8-.2-10.2 15.4-11.1 28.7-25 39.3-40.8z"/></svg><p>Twitter</p></a></li><li><a href="https://www.facebook.com/sharer.php?u=https%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f" target=_blank rel=noopener aria-label="Share on Facebook" class="share-btn facebook"><svg class="widget-social__link-icon icon icon-facebook" width="24" height="24" viewBox="0 0 352 352"><path d="m0 32v288c0 17.5 14.5 32 32 32h288c17.5.0 32-14.5 32-32V32c0-17.5-14.5-32-32-32H32C14.5.0.0 14.5.0 32zm320 0v288h-83V212h41.5l6-48H237v-31c0-14 3.5-23.5 23.5-23.5h26V66c-4.4-.6-19.8-1.5-37.5-1.5-36.9.0-62 22.2-62 63.5v36h-42v48h42v108H32V32z"/></svg><p>Facebook</p></a></li><li><a href="https://www.linkedin.com/shareArticle?mini=true&url=https%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f&source=https%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f&title=Error%20Handling%20in%20JavaScript&summary=Error%20Handling%20in%20JavaScript" target=_blank rel=noopener aria-label="Share on LinkedIn" class="share-btn linkedin"><svg class="widget-social__link-icon icon icon-linkedin" width="24" height="24" viewBox="0 0 352 352"><path d="M0 40v272c0 21.9 18.1 40 40 40h272c21.9.0 40-18.1 40-40V40c0-21.9-18.1-40-40-40H40C18.1.0.0 18.1.0 40zm312-8c4.6.0 8 3.4 8 8v272c0 4.6-3.4 8-8 8H40c-4.6.0-8-3.4-8-8V40c0-4.6 3.4-8 8-8H312zM59.5 87c0 15.2 12.3 27.5 27.5 27.5s27.5-12.3 27.5-27.5S102.2 59.5 87 59.5 59.5 71.8 59.5 87zM187 157h-1v-21h-45v152h47v-75c0-19.8 3.9-39 28.5-39 24.2.0 24.5 22.4 24.5 40v74h47v-83.5c0-40.9-8.7-72-56.5-72C208.5 132.5 193.3 145.1 187 157zM64 288h47.5V136H64V288z"/></svg><p>LinkedIn</p></a></li><li><a href="whatsapp://send?text=Error%20Handling%20in%20JavaScript%2c%20by%20Coding%20N%20Concepts%0aIn%20this%20tutorial%2c%20we%27ll%20learn%20error%20handling%20using%20try%2c%20catch%2c%20finally%20and%20throw%20statements.%20We%27ll%20also%20learn%20about%20built-in%20JavaScript%20error%20objects%20%28Error%2c%20SyntaxError%2c%20ReferenceError%2c%20etc.%29%20and%20how%20to%20define%20custom%20errors.%0a%0ahttps%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f%0a" target=_blank class="share-btn whatsapp"><svg class="widget-social__link-icon icon icon-whatsapp" width="24" height="24" viewBox="0 0 24 24"><path d="M20.1 3.9C17.9 1.7 15 .5 12 .5 5.8.5.7 5.6.7 11.9c0 2 .5 3.9 1.5 5.6L.6 23.4l6-1.6c1.6.9 3.5 1.3 5.4 1.3 6.3.0 11.4-5.1 11.4-11.4-.1-2.8-1.2-5.7-3.3-7.8zM12 21.4c-1.7.0-3.3-.5-4.8-1.3l-.4-.2-3.5 1 1-3.4L4 17c-1-1.5-1.4-3.2-1.4-5.1.0-5.2 4.2-9.4 9.4-9.4 2.5.0 4.9 1 6.7 2.8s2.8 4.2 2.8 6.7c-.1 5.2-4.3 9.4-9.5 9.4zm5.1-7.1c-.3-.1-1.7-.9-1.9-1-.3-.1-.5-.1-.7.1-.2.3-.8 1-.9 1.1-.2.2-.3.2-.6.1s-1.2-.5-2.3-1.4c-.9-.8-1.4-1.7-1.6-2s0-.5.1-.6.3-.3.4-.5c.2-.1.3-.3.4-.5s0-.4.0-.5C10 9 9.3 7.6 9 7c-.1-.4-.4-.3-.5-.3h-.6s-.4.1-.7.3c-.3.3-1 1-1 2.4s1 2.8 1.1 3c.1.2 2 3.1 4.9 4.3.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.6-.1 1.7-.7 1.9-1.3.2-.7.2-1.2.2-1.3-.1-.3-.3-.4-.6-.5z"/></svg><p>Email</p></a></li><li><a href="mailto:?subject=Coding%20N%20Concepts - Error%20Handling%20in%20JavaScript.&body=Error%20Handling%20in%20JavaScript%2c%20by%20Coding%20N%20Concepts%0aIn%20this%20tutorial%2c%20we%27ll%20learn%20error%20handling%20using%20try%2c%20catch%2c%20finally%20and%20throw%20statements.%20We%27ll%20also%20learn%20about%20built-in%20JavaScript%20error%20objects%20%28Error%2c%20SyntaxError%2c%20ReferenceError%2c%20etc.%29%20and%20how%20to%20define%20custom%20errors.%0a%0ahttps%3a%2f%2fcodingnconcepts.com%2fjavascript%2ferror-handling-in-javascript%2f%0a" target=_blank class="share-btn email"><svg class="widget-social__link-icon icon icon-mail" width="24" height="24" viewBox="0 0 416 288"><path d="m0 16v256 16h16 384 16v-16V16 0h-16H16 0zm347 16-139 92.5L69 32zM199 157.5l9 5.5 9-5.5L384 46v210H32V46z"/></svg><p>Email</p></a></li></ul></section><div class=related_post_section><h2 class=related_post_title>See Also</h2><ul class=related_post><li><a href=/javascript/how-to-replace-all-occurrences-string-javascript/>How to Replace all Occurrences of a String in JavaScript</a></li><li><a href=/javascript/math-constants-and-functions-in-javascript/>Math Constants and Functions in JavaScript</a></li><li><a href=/javascript/how-to-capitalize-first-letter-of-string-in-javascript/>How to Capitalize First Letter of String in JavaScript</a></li><li><a href=/javascript/comparison-operators-in-javascript/>Difference in == and === comparison operators in JavaScript</a></li><li><a href=/javascript/this-keyword-in-javascript/>Understand all about this keyword in JavaScript</a></li></ul></div><div class="authorbox clearfix"><figure class=authorbox__avatar><img alt="Ashish Lahoti avatar" src=/media/authors/ashishlahoti.png class=avatar height=90 width=90></figure><div class=authorbox__header><span class=authorbox__name>About Ashish Lahoti</span></div><div class=authorbox__description>Ashish Lahoti is a senior application developer at DBS Bank having 10+ years of experience in full stack technologies | Confluent Certified Developer for Apache KAFKA | SCJP Certified</div></div><nav class="post-nav flex"><div class="post-nav__item post-nav__item--prev"><a class=post-nav__link href=/javascript/difference-between-foreach-and-map-in-javascript-array/ rel=prev><span class=post-nav__caption>«&#8201;Previous</span><p class=post-nav__post-title>Difference Between forEach() and map() in JavaScript Array</p></a></div></nav><section class=comments><div id=disqus_thread></div><script type=application/javascript>var disqus_config=function(){};(function(){if(["localhost","127.0.0.1"].indexOf(window.location.hostname)!=-1){document.getElementById('disqus_thread').innerHTML='Disqus comments not available by default when the website is previewed locally.';return;}
var d=document,s=d.createElement('script');s.async=true;s.src='//'+"codingnconcepts"+'.disqus.com/embed.js';s.setAttribute('data-timestamp',+new Date());(d.head||d.body).appendChild(s);})();</script><noscript>Please enable JavaScript to view the <a href=https://disqus.com/?ref_noscript>comments powered by Disqus.</a></noscript><a href=https://disqus.com class=dsq-brlink>comments powered by <span class=logo-disqus>Disqus</span></a></section></div></div><footer class=footer><div class="container footer__container flex"><div class=footer__copyright>&copy; 2020 CodingNConcepts.
<span class=footer__copyright-credits>Generated with <a href=https://gohugo.io/ rel="nofollow noopener" target=_blank>Hugo</a> and <a href=https://github.com/Vimux/Mainroad/ rel="nofollow noopener" target=_blank>Mainroad</a> theme.</span></div></div></footer></div><script async defer src=/js/menu.js></script></body></html>